### ISSUE TITLE
插件报json error错误

### ISSUE THREAD

**Issue by match08** [wojor/cordova-ilex-weixin-plugin#1]
插件报json error错误，这没具体点的？ 是参数还是什么错误。json格式肯定是对的

**Comment by chinavane** [comment]
能否提供一下具体调用的示例代码？也就是那个json的数据格式。

**Comment by xujinyao** [comment]
var params = {
              'appid': payParams['app_id'],
              'noncestr': payParams['nonce_str'],
              'package': payParams['package'],
              'partnerid': payParams['partner_id'],
              'prepayid': payParams['prepay_id'],
              'timestamp': payParams['timestamp'],
              'sign': payParams['sign']
            };
Wechat.payment(params, function () {
    //success
  }, function (error) {

  });
